'use strict';

module.exports = {
    "Bulova Automatic": "Bulova",
    "Bulova N3": "Bulova",
    "Baume &amp; Mercier": "Baume & Mercier",
    "Bell &amp; Ross": "Bell & Ross",
    "Bvlgari": "Bulgari",
    "CITIZEN": "Citizen",
    "Calvin Klein": "Calvin Klein",
    "Citizen Ace": "Citizen",
    "Citizen Crystate DeLuxe": "Citizen",
    "Citizen DeLuxe": "Citizen",
    "Citizen Homer": "Citizen",
    "CHAUMET": "Chaumet",
    "Cortebert 350 Electronic Watch": "Cortebert",
    "Fossil Batman Watch": "Fossil",
    "Gucci Swiss Watch": "Gucci",
    "GUCCI": "Gucci",
    "Jaeger LeCoultre": "Jaeger-LeCoultre",
    "FENDI": "Fendi",
    "FOCE": "Foce",
    "EBEL": "Ebel",
    "FORTIS": "Fortis",
    "GUESS": "Guess",
    "Elcanto": "El Canto",
    "LeCoultre": "Jaeger-LeCoultre",
    "Longine": "Longines",
    "Longines Swiss Watch": "Longines",
    "Omega Constellation": "OMEGA",
    "Omega Constellation Chronometer": "Omega",
    "Omega Geneve": "Omega",
    "Omega": "Omega",
    "ORIENT STAR": "Orient Star",
    "Rado Watch": "Rado",
    "Rolex Tudor": "Tudor",
    "Rolex Tudor Watch": "Tudor",
    "TUDOR": "Tudor",
    "Tugaris": "Tugaris",
    "Tag Heuer": "TAG Heuer",
    "Tiffany &amp; Co.": "Tiffany & Co.",
    "TECHNOMARINE": "TechnoMarine",
    "Rolex Orchid": "Rolex",
    "Rolex Cellini": "Rolex",
    "RAYMOND WEIL": "Raymond Weil",
    "Seiko Champion": "Seiko",
    "Seiko Laurel": "Seiko",
    "Seiko LM": "Seiko",
    "Seiko Sportsman": "Seiko",
    "Swiss Military Watch": "Swiss Military",
    "Technos Watch": "Technos",
    "Universal Genève": "Universal Geneve",
    "Valruz Triple Calendar Watch": "Valruz",
    "Zenith": "Zenith",
    "Van Cleef &amp; Arpels": "Van Cleef & Arpels"
};
